version: "3.7"
services:
  zookeeper1:
    entrypoint: /bin/bash run-zookeeper.sh --myid 1
    image: "docker.io/dockeralexandrtalan/zookeeper"
    volumes:
      - ./zookeeper-config:/usr/local/lib/apache-zookeeper-3.5.6-bin/conf
    ports:
      - "2181:2181"
    networks:
      - kafka
  zookeeper2:
    entrypoint: /bin/bash run-zookeeper.sh --myid 2
    image: "docker.io/dockeralexandrtalan/zookeeper"
    volumes:
      - ./zookeeper-config:/usr/local/lib/apache-zookeeper-3.5.6-bin/conf
    ports:
      - "2182:2181"
    networks:
      - kafka
  zookeeper3:
    entrypoint: /bin/bash run-zookeeper.sh --myid 3
    image: "docker.io/dockeralexandrtalan/zookeeper"
    volumes:
      - ./zookeeper-config:/usr/local/lib/apache-zookeeper-3.5.6-bin/conf
    ports:
      - "2183:2181"
    networks:
      - kafka

  kafka1:
    entrypoint: /bin/bash entrypoint.sh --config /usr/local/lib/kafka_2.12-2.4.0/config/kafka.json --id 1
    image: "docker.io/dockeralexandrtalan/kafka"
    volumes:
      - ./kafka-config:/usr/local/lib/kafka_2.12-2.4.0/config/
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper1
    networks:
      - kafka
  kafka2:
    entrypoint: /bin/bash entrypoint.sh --config /usr/local/lib/kafka_2.12-2.4.0/config/kafka.json --id 2
    image: "docker.io/dockeralexandrtalan/kafka"
    volumes:
      - ./kafka-config:/usr/local/lib/kafka_2.12-2.4.0/config/
    ports:
      - "9093:9092"
    depends_on:
      - zookeeper1
    networks:
      - kafka
  kafka3:
    entrypoint: /bin/bash entrypoint.sh --config /usr/local/lib/kafka_2.12-2.4.0/config/kafka.json --id 3
    image: "docker.io/dockeralexandrtalan/kafka"
    volumes:
      - ./kafka-config:/usr/local/lib/kafka_2.12-2.4.0/config/
    ports:
      - "9094:9092"
    depends_on:
      - zookeeper1
    networks:
      - kafka

networks:
  kafka: